//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int ID { get; set; }
        public string PostTitle { get; set; }
        public string PostBody { get; set; }
        public Nullable<int> PostAuthor { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public string PostRelType { get; set; }
        public Nullable<int> PostRelTo { get; set; }
    
        public virtual User User { get; set; }
    }
}
